#!/usr/bin/env python
# python list_icons

import gtk
# lists icons supported in your current theme,
# so yeah, what the name says
icon_theme = gtk.icon_theme_get_default()
l =  icon_theme.list_icons()

for each in sorted(l):
    if 'stock' in each:
        print each
